### ISSUE TITLE
[Improvement] Add callback functions

### ISSUE THREAD

**Issue by claudchan** [istvan-ujjmeszaros/bootstrap-autohidingnavbar#11]
Hi,
Can add callback functions?
onOpen, onClose, onHidden, onScroll, etc...

**Comment by vladimirnani** [comment]
Resolves with #13

**Comment by vladimirnani** [comment]
- show.autoHidingNavbar triggers when element is shown.
- hide.autoHidingNavbar triggers when element is hidden.

That`s probably enough
