### ISSUE TITLE
sbt

### ISSUE THREAD

**Issue by songoo** [istvan-ujjmeszaros/bootstrap-autohidingnavbar#21]
For some reason few days ago after sbt reload, autohidingnavbar dependency started to downloading boostrap 4.0.0-aplha, which owerride my web 3.3.1 boostrap causing unwanted layout changes.

Not sure what exactly cause it , maybe somehow this bower annotation ? :
"bootstrap": ">=3.0.0"

**Comment by istvan-ujjmeszaros** [comment]
I have just published a new version with "~3.0", can you try if it works as expected?

**Comment by songoo** [comment]
This should work right, could not test since cant see 1.0.3 on bower for some reason (http://www.webjars.org/bower show 1.0.2 as latest) maybe it need time ?

**Comment by istvan-ujjmeszaros** [comment]
No, I have forgot to update the version number... I have published a new version (1.0.4), again :)

**Comment by songoo** [comment]
Tnx much, everything is working fine now . :+1:

**Comment by istvan-ujjmeszaros** [comment]
Thanks for the feedback!
