### ISSUE TITLE
Bug when navbar has top or bottom padding

### ISSUE THREAD

**Issue by andrearufo** [istvan-ujjmeszaros/bootstrap-autohidingnavbar#3]
If change the navbar style adding padding, the script not set the correct measure to hide the navbar.
Fix is really simple: change the `height()` function at row 43 with `innerHeight()`.

Thank you for your work!

**Comment by istvan-ujjmeszaros** [comment]
Fixed in 52eb7784e55715fcc99f59e954be15e22f082ad1
